## Sample Pod YAML file used in example (called pod.yml in video):

apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-00
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-ctr
    image: nigelpoulton/pluralsight-docker-ci:latest
    ports:
    - containerPort: 8080
